tunnel: my-tunnel
credentials-file: .cloudflared/tunnel-secrets.json

ingress:
  - hostname: lab.eliam-lotonga.fr
    service: http://traefik
  - hostname: traefik.eliam-lotonga.fr
    service: http://traefik
  - service: http_status:404
