global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG
accessLog:
  format: "json"

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
